commandline: fix argument handling for ghc-7.2+ ('gtg' this time)
The build breakage on ghc-7.4 was introduced
in 'commit ba5f07dc66621321cd573ce3869fd856946ed57b'

    [7 of 7] Compiling Main             ( Gtg/gtg.hs, dist/build/gtg/gtg-tmp/Main.o )
    Gtg/gtg.hs:21:13:
        Not in scope: `getArgs'
        Perhaps you meant `U.getArgs' (imported from System.Environment.UTF8)

Added missing 'System.Environment' import

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>